security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_EMPLOYEE:       ROLE_USER
        ROLE_ADMIN:       ROLE_EMPLOYEE
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 3024000 # 1 week in seconds
                path:     /
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/utilisateur/ajax/, role: ROLE_EMPLOYEE }
        - { path: ^/admin/livre/ajax/, role: ROLE_EMPLOYEE }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/emprunt/, role: ROLE_EMPLOYEE }
