<?php

namespace DalBundle\Repository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByName($search)
    {
        $query = $this->createQueryBuilder('a')
            ->select(' a.id, (CASE WHEN (a.prenom is not null) THEN CONCAT(a.nom, \' \', a.prenom) ELSE a.nom END )as value')
            ->orderBy('a.nom', 'ASC')
            ->addOrderBy('a.prenom', 'ASC')
            ->where('a.nom LIKE :search')
            ->setParameter('search', $search . "%");

        return $query->getQuery()->getResult();
    }
}
