<?php

namespace DalBundle\Repository;

use DalBundle\Entity\Livre;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumeroSuivant()
    {
        /** @var Livre[] $livres */
        $livres = $this->findBy([], ["numero" => 'ASC']);
        $i = 1;
        foreach ($livres AS $livre) {
            if ($livre->getNumero() == $i) {
                $i++;
                continue;
            } else {
                return $i;
            }
        }
        return $i;
    }

    public function findByAnything($search)
    {

        $query = $this->createQueryBuilder('l')
            ->leftJoin('l.keywords', 'k')
            ->leftJoin('l.auteur', 'a')
            ->leftJoin('l.categorie', 'c')
            ->where('l.titre LIKE :search')
            ->orWhere('a.nom LIKE :search')
            ->orWhere('a.prenom LIKE :search')
            ->orWhere('c.libelle LIKE :search')
            ->orWhere('k.libelle LIKE :search')
            ->orderBy('l.titre')
            ->setParameter('search', '%' . $search . '%');

        return $query->getQuery()->getResult();
    }
}
