<?php

namespace DalBundle\Repository;

/**
 * UploadDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
