admin_auteur_index:
    path:     /
    defaults: { _controller: "DalBundle:Auteur:index" }
    methods:  GET

admin_auteur_show:
    path:     /{id}/show
    defaults: { _controller: "DalBundle:Auteur:show" }
    methods:  GET

admin_auteur_new:
    path:     /new
    defaults: { _controller: "DalBundle:Auteur:new" }
    methods:  [GET, POST]

admin_auteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "DalBundle:Auteur:edit" }
    methods:  [GET, POST]

admin_auteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "DalBundle:Auteur:delete" }
    methods:  DELETE

auteur_resource:
    path:     /autocomplete
    defaults: { _controller: "DalBundle:Auteur:autocomplete" }
    methods:  [GET, POST]