admin_livre_index:
    path:     /
    defaults: { _controller: "DalBundle:Livre:index" }
    methods:  GET

admin_livre_show:
    path:     /{id}/show
    defaults: { _controller: "DalBundle:Livre:show" }
    methods:  GET

admin_livre_new:
    path:     /new
    defaults: { _controller: "DalBundle:Livre:new" }
    methods:  [GET, POST]

admin_livre_edit:
    path:     /{id}/edit
    defaults: { _controller: "DalBundle:Livre:edit" }
    methods:  [GET, POST]

admin_livre_delete:
    path:     /{id}/delete
    defaults: { _controller: "DalBundle:Livre:delete" }
    methods:  DELETE

livre_resource:
    path:     /ajax/
    defaults: { _controller: "DalBundle:Livre:ajax" }